### ISSUE TITLE
obp-utils depends on pandoc

### ISSUE THREAD

**Issue by Tubbebubbe** [atmel-maxtouch/obp-utils#8]
It seems obp-utils uses pandoc when installing man pages. No other recipe provides pandoc, and I guess it's taken from the host.

**Comment by Tubbebubbe** [comment]
How about splitting the package, moving README.md into obd-utils-docs (which may depend on pandoc) and let the rest build without pandoc.

A recipe should of course also be added to provide pandoc, so that obd-utils-docs doesn't depend on binaries on the host.

**Comment by ndyer** [comment]
Can you provide some context here? You are talking about packages, recipes, none of which makes sense to me. Are you using a build script that is part of some other system?

**Comment by Tubbebubbe** [comment]
I'm really sorry! This was never meant for you or the obp-utils source repo. The problem I'm trying to explain is about the Yocto / Bitbake package "obp-utils" in meta-atmel (Yocto) repository. 

Again, I am truly sorry for the comments and wasting your time!

**Comment by ndyer** [comment]
No worries:

FWIW I guess you mean this:
https://github.com/linux4sam/meta-atmel/blob/master/recipes-utils/obp-utils/obp-utils_git.bb
